"""gerenciador_pessoas_schema_inicial

Revision ID: 7c8217112386
Revises: 
Create Date: 2026-09-07 18:37:49.700771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7c8217112386'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('alcunha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('documento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('antecedentes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dados_aj', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('qrb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_externa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome_local', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('municipio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endereco', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('coordenadas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tipo_local', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('foto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_externa')
    )
    op.create_table('veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('placa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('localizacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('proprietario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('foto_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('grupos_criminosos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_externa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qrb_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['qrb_id'], ['qrb.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_externa')
    )
    op.create_table('grupos_familiares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_externa', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qrb_id', sa.Integer(), nullable=True),
    sa.Column('observacao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['qrb_id'], ['qrb.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave_externa')
    )
    op.create_table('pessoa_fotos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('caminho_arquivo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa_qrb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('qrb_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['qrb_id'], ['qrb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa_veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('data_posse', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa_grupo_criminoso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('grupo_criminoso_id', sa.Integer(), nullable=False),
    sa.Column('funcao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_criminoso_id'], ['grupos_criminosos.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pessoa_grupo_familiar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.Column('grupo_familiar_id', sa.Integer(), nullable=False),
    sa.Column('funcao', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['grupo_familiar_id'], ['grupos_familiares.id'], ),
    sa.ForeignKeyConstraint(['pessoa_id'], ['pessoas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pessoa_grupo_familiar')
    op.drop_table('pessoa_grupo_criminoso')
    op.drop_table('pessoa_veiculo')
    op.drop_table('pessoa_qrb')
    op.drop_table('pessoa_fotos')
    op.drop_table('grupos_familiares')
    op.drop_table('grupos_criminosos')
    op.drop_table('veiculos')
    op.drop_table('qrb')
    op.drop_table('pessoas')
    # ### end Alembic commands ###
